### ISSUE TITLE
How to decode websocket frame ?

### ISSUE THREAD

**Issue by johnzeng** [openresty/lua-resty-websocket#19]
I wanna decode the frames and wait for a special frame, after decoding and analyzing this frame, I will disconnect it or let it pass. But this module just recv the frame and never put it back, so it can be a websocket server, but can't be a proxy for websocket.

Any idea to make it a proxy for websocket?

**Comment by agentzh** [comment]
@johnzeng This library provides both a client and a server for websocket. You need need to connect the client with the server at the same time to form a websocket proxy.

**Comment by johnzeng** [comment]
Yeah....I get that from your mail list. Another question, how can I detect websocket closing if client closes the page without sending a close frame?

**Comment by agentzh** [comment]
@johnzeng Please use the mailing list for such questions. This place is for real issues in the code base. Thank you.

**Comment by johnzeng** [comment]
Giving an example which will end up with tons of time out error should be an code base issue.
