### ISSUE TITLE
[alert] 3422#0: worker process 4444 exited on signal 11 (core dumped)?

### ISSUE THREAD

**Issue by dayongi** [openresty/lua-resty-websocket#41]
I wrote a simple API gateway, but during the test, I found that the process would suddenly exit within a certain period of time, resulting in disconnection. I thought it was the workers who did not share SSL information, but after consulting the data, I felt it was not the problem of SSL and fell into a confused state. I would like to ask what the problem was caused by?thank you

**problem：**
![image](https://user-images.githubusercontent.com/41787764/53705164-6b06d000-3e5d-11e9-93bd-08a3dc86ecce.png)

**problem：**
![image](https://user-images.githubusercontent.com/41787764/53705167-722dde00-3e5d-11e9-8faa-f35f12e01264.png)

**client code：**
![image](https://user-images.githubusercontent.com/41787764/53705219-c20ca500-3e5d-11e9-937d-224be47d9128.png)

**server code :**
![image](https://user-images.githubusercontent.com/41787764/53705233-d2248480-3e5d-11e9-993e-a2f2ab1ff4e0.png)

**Comment by agentzh** [comment]
@dayongi Looks like you are using incompatible components. But to be sure, you need to provide the full C backtrace for the core dump. See https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump

Will you just try the latest OpenResty version below?

https://openresty.org/en/ann-1015008001rc1.html

You didn't mention how you build your thing and what version of software you are using.

**Comment by dayongi** [comment]
@agentzh   I‘m using openresty/1.13.6.2
I checked my code yesterday and found that the problem seems to be Shared. I modified the code and now it seems ok.

**Comment by agentzh** [comment]
Consider it resolved then.
